# Generated by Django 3.2.18 on 2023-04-27 00:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Inventory',
            fields=[
                ('item_ID', models.IntegerField(primary_key=True, serialize=False)),
                ('item_name', models.CharField(max_length=100)),
                ('quantity', models.IntegerField()),
                ('item_cost', models.DecimalField(decimal_places=2, max_digits=10)),
                ('product_type', models.CharField(max_length=30)),
                ('product_size', models.CharField(max_length=15)),
                ('product_color', models.CharField(max_length=15)),
                ('product_description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Sales',
            fields=[
                ('salesID', models.IntegerField(primary_key=True, serialize=False)),
                ('salesDate', models.DateField()),
                ('salesQuantity', models.IntegerField()),
                ('salesTotal', models.DecimalField(decimal_places=2, max_digits=10)),
                ('productID', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='inventory.inventory')),
            ],
        ),
    ]
